"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const bridge = {
    ready: () => electron_1.ipcRenderer.invoke('app-ready'),
    saveSettings: (settings) => electron_1.ipcRenderer.invoke('save-settings', settings),
    generateQr: () => electron_1.ipcRenderer.invoke('generate-qr'),
    captureNow: () => electron_1.ipcRenderer.invoke('capture-now'),
    openGemini: () => electron_1.ipcRenderer.invoke('open-gemini'),
    focusGemini: () => electron_1.ipcRenderer.invoke('focus-gemini'),
    setSelection: (payload) => electron_1.ipcRenderer.invoke('set-selection', payload),
    cancelSelection: () => electron_1.ipcRenderer.invoke('cancel-selection'),
    setAnnotated: (hasAnnotations) => electron_1.ipcRenderer.invoke('set-annotated', hasAnnotations),
    onStatus: (callback) => electron_1.ipcRenderer.on('status', (_, message) => callback(message)),
    onResponse: (callback) => electron_1.ipcRenderer.on('response', (_, message) => callback(message)),
    onOverlayState: (callback) => electron_1.ipcRenderer.on('overlay-state', (_, state) => callback(state)),
    onOverlayMessage: (callback) => electron_1.ipcRenderer.on('overlay-message', (_, message) => callback(message)),
    confirmSelectionGemini: () => electron_1.ipcRenderer.invoke('confirm-selection-gemini'),
    confirmSelectionPhone: () => electron_1.ipcRenderer.invoke('confirm-selection-phone'),
    confirmSelectionOcr: () => electron_1.ipcRenderer.invoke('confirm-selection-ocr'),
    getStorageUsage: () => electron_1.ipcRenderer.invoke('get-storage-usage'),
    purgeStorage: () => electron_1.ipcRenderer.invoke('purge-storage'),
    setupRls: () => electron_1.ipcRenderer.invoke('setup-rls'),
    sendClipboard: () => electron_1.ipcRenderer.invoke('send-clipboard'),
    panelToggle: () => electron_1.ipcRenderer.invoke('panel-toggle'),
    panelInteractStart: () => electron_1.ipcRenderer.invoke('panel-interact-start'),
    panelDragBy: (dx, dy) => electron_1.ipcRenderer.invoke('panel-drag-by', dx, dy),
    panelDismiss: () => electron_1.ipcRenderer.invoke('panel-dismiss'),
    savePanelPinned: (pinned) => electron_1.ipcRenderer.invoke('panel-save-pinned', pinned),
    panelResizeCompact: (size) => electron_1.ipcRenderer.invoke('panel-resize-compact', size),
    onPanelMode: (callback) => electron_1.ipcRenderer.on('panel-mode', (_, mode) => callback(mode)),
    onHudCapturing: (callback) => electron_1.ipcRenderer.on('hud-capturing', (_, active) => callback(active)),
    onPillDragState: (callback) => electron_1.ipcRenderer.on('pill-drag-state', (_, dragging) => callback(dragging)),
    onPillResized: (callback) => electron_1.ipcRenderer.on('pill-resized', (_, size) => callback(size)),
};
electron_1.contextBridge.exposeInMainWorld('bridge', bridge);
