"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const electron_1 = require("electron");
const bridge = {
    ready: () => electron_1.ipcRenderer.invoke('app-ready'),
    saveSettings: (settings) => electron_1.ipcRenderer.invoke('save-settings', settings),
    generateQr: () => electron_1.ipcRenderer.invoke('generate-qr'),
    captureNow: () => electron_1.ipcRenderer.invoke('capture-now'),
    openGemini: () => electron_1.ipcRenderer.invoke('open-gemini'),
    focusGemini: () => electron_1.ipcRenderer.invoke('focus-gemini'),
    notifyOverlayReady: () => electron_1.ipcRenderer.invoke('overlay-renderer-ready'),
    notifyOverlayRendered: (sessionId) => electron_1.ipcRenderer.invoke('overlay-rendered', sessionId),
    setSelection: (payload) => electron_1.ipcRenderer.invoke('set-selection', payload),
    cancelSelection: (sessionId) => electron_1.ipcRenderer.invoke('cancel-selection', sessionId),
    setAnnotated: (payload) => electron_1.ipcRenderer.invoke('set-annotated', payload),
    startSelectionDrag: (sessionId) => electron_1.ipcRenderer.send('start-selection-drag', sessionId),
    onSelectionDragState: (callback) => electron_1.ipcRenderer.on('selection-drag-state', (_, data) => callback(data)),
    copySelection: (sessionId) => electron_1.ipcRenderer.invoke('copy-selection', sessionId),
    onStatus: (callback) => electron_1.ipcRenderer.on('status', (_, message) => callback(message)),
    onResponse: (callback) => electron_1.ipcRenderer.on('response', (_, message) => callback(message)),
    onOverlayState: (callback) => electron_1.ipcRenderer.on('overlay-state', (_, state) => callback(state)),
    onOverlayMessage: (callback) => electron_1.ipcRenderer.on('overlay-message', (_, message) => callback(message)),
    confirmSelectionGemini: (sessionId) => electron_1.ipcRenderer.invoke('confirm-selection-gemini', sessionId),
    confirmSelectionPhone: (sessionId) => electron_1.ipcRenderer.invoke('confirm-selection-phone', sessionId),
    confirmSelectionOcr: (sessionId) => electron_1.ipcRenderer.invoke('confirm-selection-ocr', sessionId),
    getStorageUsage: () => electron_1.ipcRenderer.invoke('get-storage-usage'),
    purgeStorage: () => electron_1.ipcRenderer.invoke('purge-storage'),
    setupRls: () => electron_1.ipcRenderer.invoke('setup-rls'),
    sendClipboard: () => electron_1.ipcRenderer.invoke('send-clipboard'),
    panelToggle: () => electron_1.ipcRenderer.invoke('panel-toggle'),
    panelInteractStart: () => electron_1.ipcRenderer.invoke('panel-interact-start'),
    panelDragBy: (dx, dy) => electron_1.ipcRenderer.invoke('panel-drag-by', dx, dy),
    panelDismiss: () => electron_1.ipcRenderer.invoke('panel-dismiss'),
    quitApp: () => electron_1.ipcRenderer.invoke('app-quit'),
    savePanelPinned: (pinned) => electron_1.ipcRenderer.invoke('panel-save-pinned', pinned),
    panelResizeCompact: (size) => electron_1.ipcRenderer.invoke('panel-resize-compact', size),
    onPanelMode: (callback) => electron_1.ipcRenderer.on('panel-mode', (_, mode) => callback(mode)),
    onHudCapturing: (callback) => electron_1.ipcRenderer.on('hud-capturing', (_, active) => callback(active)),
    onPillDragState: (callback) => electron_1.ipcRenderer.on('pill-drag-state', (_, dragging) => callback(dragging)),
    onPillResized: (callback) => electron_1.ipcRenderer.on('pill-resized', (_, size) => callback(size)),
    onNotification: (callback) => electron_1.ipcRenderer.on('show-notification', (_, data) => callback(data)),
    onDismissNotification: (callback) => electron_1.ipcRenderer.on('dismiss-notification', () => callback()),
    uploadFileToPhone: (filePath) => electron_1.ipcRenderer.invoke('upload-file-to-phone', filePath),
    startDragDownloadedFile: (filePath) => electron_1.ipcRenderer.send('start-drag-downloaded-file', filePath),
    deleteDownloadedFile: (filePath) => electron_1.ipcRenderer.invoke('delete-downloaded-file', filePath),
    onPhoneDownloadsUpdated: (callback) => electron_1.ipcRenderer.on('phone-downloads-updated', (_, files) => callback(files)),
};
electron_1.contextBridge.exposeInMainWorld('bridge', bridge);
