import { contextBridge, ipcRenderer } from 'electron';
import type { BridgeAPI } from './types';

const bridge: BridgeAPI = {
  ready: () => ipcRenderer.invoke('app-ready'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  generateQr: () => ipcRenderer.invoke('generate-qr'),
  captureNow: () => ipcRenderer.invoke('capture-now'),
  openGemini: () => ipcRenderer.invoke('open-gemini'),
  focusGemini: () => ipcRenderer.invoke('focus-gemini'),
  notifyOverlayReady: () => ipcRenderer.invoke('overlay-renderer-ready'),
  notifyOverlayRendered: (sessionId) => ipcRenderer.invoke('overlay-rendered', sessionId),
  setSelection: (payload) => ipcRenderer.invoke('set-selection', payload),
  cancelSelection: (sessionId) => ipcRenderer.invoke('cancel-selection', sessionId),
  setAnnotated: (payload) => ipcRenderer.invoke('set-annotated', payload),
  startSelectionDrag: (sessionId) => ipcRenderer.send('start-selection-drag', sessionId),
  onSelectionDragState: (callback) =>
    ipcRenderer.on('selection-drag-state', (_, data) => callback(data)),
  copySelection: (sessionId) => ipcRenderer.invoke('copy-selection', sessionId),
  onStatus: (callback) => ipcRenderer.on('status', (_, message) => callback(message)),
  onResponse: (callback) => ipcRenderer.on('response', (_, message) => callback(message)),
  onOverlayState: (callback) => ipcRenderer.on('overlay-state', (_, state) => callback(state)),
  onOverlayMessage: (callback) =>
    ipcRenderer.on('overlay-message', (_, message) => callback(message)),
  confirmSelectionGemini: (sessionId) => ipcRenderer.invoke('confirm-selection-gemini', sessionId),
  confirmSelectionPhone: (sessionId) => ipcRenderer.invoke('confirm-selection-phone', sessionId),
  confirmSelectionOcr: (sessionId) => ipcRenderer.invoke('confirm-selection-ocr', sessionId),
  getStorageUsage: () => ipcRenderer.invoke('get-storage-usage'),
  purgeStorage: () => ipcRenderer.invoke('purge-storage'),
  setupRls: () => ipcRenderer.invoke('setup-rls'),
  sendClipboard: () => ipcRenderer.invoke('send-clipboard'),
  panelToggle: () => ipcRenderer.invoke('panel-toggle'),
  panelInteractStart: () => ipcRenderer.invoke('panel-interact-start'),
  panelDragBy: (dx, dy) => ipcRenderer.invoke('panel-drag-by', dx, dy),
  panelDismiss: () => ipcRenderer.invoke('panel-dismiss'),
  quitApp: () => ipcRenderer.invoke('app-quit'),
  savePanelPinned: (pinned) => ipcRenderer.invoke('panel-save-pinned', pinned),
  panelResizeCompact: (size) => ipcRenderer.invoke('panel-resize-compact', size),
  onPanelMode: (callback) => ipcRenderer.on('panel-mode', (_, mode) => callback(mode)),
  onHudCapturing: (callback) => ipcRenderer.on('hud-capturing', (_, active) => callback(active)),
  onPillDragState: (callback) => ipcRenderer.on('pill-drag-state', (_, dragging) => callback(dragging)),
  onPillResized: (callback) => ipcRenderer.on('pill-resized', (_, size) => callback(size)),
  onNotification: (callback) => ipcRenderer.on('show-notification', (_, data) => callback(data)),
  onDismissNotification: (callback) => ipcRenderer.on('dismiss-notification', () => callback()),
  uploadFileToPhone: (filePath) => ipcRenderer.invoke('upload-file-to-phone', filePath),
  startDragDownloadedFile: (filePath) => ipcRenderer.send('start-drag-downloaded-file', filePath),
  deleteDownloadedFile: (filePath) => ipcRenderer.invoke('delete-downloaded-file', filePath),
  onPhoneDownloadsUpdated: (callback) => ipcRenderer.on('phone-downloads-updated', (_, files) => callback(files)),
};

contextBridge.exposeInMainWorld('bridge', bridge);
